### ISSUE TITLE
Normal Textures and MipMapping

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#214] opened 2020-04-06 11:19 UTC
Remove general flaws with `Texture` class and Mipmapping
---

The [`Texture` Constructor's](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/Texture.cs#L136) arguments default to 

- `bool generateMipMaps = true` and
-  `TextureFilterMode filterMode = TextureFilterMode.LINEAR`

which doesn't make sense because if you want to have mipmaps generated, you also probably want to have them used in interpolation, so `filterMode` should default to `TextureFilterMode.NEAREST_MIPMAP_LINEAR`. 

Standard OpenGL allows to specify different values for the magnification and the minification filter. Not sure, if the possibility to specify only one single filter for both works well in all possible cases.

The `TextureFilterMode` enum values should be standard C# camel case (`NearestMipmapNearest`).

It should be possible to change the [`TextureFilterMode` Property](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/Texture.cs#L92) after construction.

Make Mipmapping work with Normal maps
---
When setting `filterMode` to `TextureFilterMode.NEAREST_MIPMAP_LINEAR` the result is a surface rendered in black (possibly with some highlights), even if the normal map intensity is set to 0.0f like so:
`bumpeffect.SetEffectParam("NormalMapIntensity", 0f);`

**Comment by RedImp1470** [comment] 2020-04-23 11:57
I changed the filter mode in the default constructor to ``TextureFilterMode.NEAREST_MIPMAP_LINEAR`` and moved the ``gl.GenerateMipmap`` calls in ``RenderContextImp`` under the ``gl.TexImage`` calls (I only got black textures before I did the second part).
To me it seems like the mipmaps are working as intended now.

As for min and mag filter:  Is it possible that we want so have different filter methods when magnifying and minifying? In this case I think we should divide the filter method in the constructor into min and mag. At the moment the singe filter parameter is resolved into min and mag in ``RenderContextImp`` ([desktop version](https://github.com/FUSEEProjectTeam/Fusee/blob/f096fd870a0ec5a76ab61ab44dce778f84ca95e2/src/Engine/Imp/Graphics/Desktop/RenderContextImp.cs#L86)).

**Comment by RedImp1470** [comment] 2020-05-15 07:58
Derived ToDos:

- [x] Set default filter mode to ``TextureFilterMode.NEAREST_MIPMAP_LINEAR``
- [x] Move the ``gl.GenerateMipmap calls`` in ``RenderContextImp`` under the ``gl.TexImage`` calls 
- [x] Allow different filter methods when magnifying and minifying? No...
- [ ] Add Methods to ``Texture``, ``RC`` and ``RCI`` that allows us to change texture paramers (filter mode, possibly wrap mode) at runtime.

**Closed** 2020-07-09 10:08 UTC
Labels: bug, prio-should
